### ISSUE TITLE
Wrong customer rendered in Draft, Sent and Due tabs on Invoices page

### ISSUE THREAD

**Issue by barnzilla** [InvoiceShelf/InvoiceShelf#210]
**Describe the bug**
The wrong customer is associated with a given invoice in the `Customer` field on the `Draft`, `Sent` and `Due` tabs on the `Invoices` page. Curiously, the correct customer is associated with a given invoice in the `Customer` field on the `All` tab.

**Expected behavior**
The correct customer should render in the `Customer` field across all tabs.

**Screenshots**
When I click on the `All` tab, the customer rendered is correct:

![image](https://github.com/user-attachments/assets/725fc3b8-6eb1-42c5-b071-1ca14fefe9d6)

When I click on the `Draft` tab, the customer rendered is still (tentatively) correct:

![image](https://github.com/user-attachments/assets/d2f4f2d8-21af-42d9-9e1a-15a8c3aed6b6)

When I click on the `Sent` tab, the customer rendered is incorrect and seems to be carried over from the last tab I visited:

![image](https://github.com/user-attachments/assets/2a6c2375-ee59-42cb-9e52-161db80e3c5b)

When I click on the `Due` tab, the customer rendered is incorrect:

![image](https://github.com/user-attachments/assets/9e0694dd-aa66-4a94-8cc4-2cc8dd46c893)

If I click on the `Draft` tab after clicking on the `Sent` tab, the customer rendered is now incorrect even though it was correct when I clicked on the `Draft` tab after clicking on the `All` tab:

![image](https://github.com/user-attachments/assets/7ec6a3ef-528a-40a2-a09d-5dd516bcd797)

**Please complete the following information:**
- InvoiceShelf version: 2.0.0-RC1
- PHP version: 8.3.12
- Database type and version: MySQL 8.0.39

**Optional info**
- OS:  Ubuntu 20.04.1
- Browser: Chrome 130.0.6723.117

**Comment by rihards-simanovics** [comment]
sounds like a duplicate of #181.

**Comment by mchev** [comment]
> sounds like a duplicate of #181.
> 
> @mchev when you have a moment can you confirm?

Yes same issue. I thought it was fixed by #186 but I will take a close look.

**Comment by rihards-simanovics** [comment]
> Yes same issue. I thought it was fixed by #186 but I will take a close look.

In the issue user indicated it was for V2.0.0-RC1, so likely fixed, if you can't replicate then an upgrade would be recommended.

**Comment by barnzilla** [comment]
Thanks for looking into this! Sorry if this is duplicated. I tried to search existing issues before submitting but clearly didn't search well enough.

**Comment by rihards-simanovics** [comment]
> Thanks for looking into this! Sorry if this is duplicated. I tried to search existing issues before submitting but clearly didn't search well enough.

Hey, no worries, happens to all of us 😊.

**Comment by Pazekal90** [comment]
@rihards-simanovics:  Hey :) I have tested the 2.1.0 today. This bug is still existing in the new version. I couldn´t add it to known issues in 2.1.0 So i use a comment in here. Hope thats correct.

**Comment by mchev** [comment]
> @rihards-simanovics:  Hey :) I have tested the 2.1.0 today. This bug is still existing in the new version. I couldn´t add it to known issues in 2.1.0 So i use a comment in here. Hope thats correct. 

I plan to fix it in 2.1.1 very soon.

**Comment by rihards-simanovics** [comment]
> [@rihards-simanovics](https://github.com/rihards-simanovics): Hey :) I have tested the 2.1.0 today. This bug is still existing in the new version. I couldn´t add it to known issues in 2.1.0 So i use a comment in here. Hope thats correct.

I'll add it, thanks; I locked that issue to ensure that there is no chatting there.

**Comment by rihards-simanovics** [comment]
Hey @mchev, I've lost track of the customer rendering issue. What is still outstanding that needs to be fixed?

**Comment by Pazekal90** [comment]
> Hey [@mchev](https://github.com/mchev), I've lost track of the customer rendering issue. What is still outstanding that needs to be fixed?

Hi @rihards-simanovics , for me the issue is completely fixed in 2.1.1.
